//! Host trait implementations and registration for WASM runtime
//!
//! This module provides:
//! - Marker trait implementations for `types::Host` and `errors::Host`
//! - The public `register_host_functions()` entry point for registering all host functions
//!
//! The marker traits (`types::Host` and `errors::Host`) are generated by
//! `wasmtime::component::bindgen!` and signal to the WASM runtime that `HostState`
//! supports the type and error definitions from the core interfaces.
//!
//! The registration function uses `RuntimeHost::add_to_linker()` to automatically
//! register all 18 host functions in a single efficient call.

// Layer 1: Standard library imports
// (none)

// Layer 2: Third-party crate imports
use wasmtime::component::Linker;

// Layer 3: Internal module imports
use crate::runtime::engine::HostState;
use crate::RuntimeHost;

/// Marker trait implementation for core::types::Host
///
/// This trait is automatically generated by `wasmtime::component::bindgen!`
/// and provides type definitions for the WASM component interface.
/// The trait itself is empty (marker trait), but its implementation signals
/// that `HostState` provides these types to WASM components.
impl crate::airssys::core::types::Host for HostState {}

/// Marker trait implementation for core::errors::Host
///
/// This trait is automatically generated by `wasmtime::component::bindgen!`
/// and provides error type definitions for the WASM component interface.
/// The trait itself is empty (marker trait), but its implementation signals
/// that `HostState` supports these error types to WASM components.
impl crate::airssys::core::errors::Host for HostState {}

/// Register all host functions with the linker
///
/// This function uses the `RuntimeHost::add_to_linker()` helper generated by
/// `wasmtime::component::bindgen!` to automatically register ALL 18 host
/// functions in a single call.
///
/// # Parameters
/// - `linker` - Mutable reference to the wasmtime Linker
///
/// # Returns
/// - `Ok(())` if registration succeeds
/// - `Err(wasmtime::Error)` if registration fails
///
/// # Example
///
/// ```ignore
/// use wasmtime::component::Linker;
/// use airssys_wasm::runtime::engine::HostState;
/// use airssys_wasm::runtime::host_functions::register_host_functions;
///
/// let engine = wasmtime::component::Engine::default();
/// let mut linker = Linker::<HostState>::new(&engine);
/// register_host_functions(&mut linker)?;
/// ```
///
/// # Efficiency
///
/// This is the optimal way to register host functions. The generated
/// `RuntimeHost::add_to_linker()` helper:
/// - Registers all functions in one call (no per-function boilerplate)
/// - Uses type-safe trait methods (compiler-checked signatures)
/// - Avoids string-based function registration (error-prone)
/// - Provides automatic validation of trait implementations
pub fn register_host_functions(linker: &mut Linker<HostState>) -> wasmtime::Result<()> {
    RuntimeHost::add_to_linker(linker, |state: &mut HostState| state)
}

#[cfg(test)]
mod tests {
    use super::*;
    use wasmtime::Engine;

    #[test]
    fn test_register_host_functions() {
        let engine = Engine::default();
        let mut linker = Linker::<HostState>::new(&engine);

        let result = register_host_functions(&mut linker);
        assert!(result.is_ok(), "Host function registration should succeed");
    }
}
