[package]
name = "airssys-osl"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Time handling (ยง3.2 workspace standard)
chrono = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Async runtime
tokio = { workspace = true }
async-trait = { version = "0.1" }

# Serialization
serde = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
