[package]
name = "airssys-osl"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Time handling (ยง3.2 workspace standard)
chrono = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Async runtime
tokio = { workspace = true }
async-trait = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
# Property-based testing
proptest = { workspace = true }

# Example configurations
[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[lints]
workspace = true
