[book]
authors = ["AirsStack Team"]
language = "en"
src = "src"
title = "AirsSys OSL - OS Layer Framework"
description = "Comprehensive OS Layer Framework for system programming with security and activity logging"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/airsstack/airssys"
edit-url-template = "https://github.com/airsstack/airssys/edit/main/{path}"

[output.html.search]
enable = true
